init config for several environments
Jedisjeux/ReactNative pull request #7
Opened 2018-03-07 13:15 UTC by loic425

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| Related tickets |
| License         | MIT

2018-03-07 13:19 UTC, loic425 commented on package.json
> -    "start": "react-native-scripts start",
c'est chelou tous ces changements, à voir si on ne peut pas revenir à la config initial là dessus

2018-03-14 21:58 UTC, qmachard requested changes

2018-03-14 21:58 UTC, qmachard commented on .babelrc
> +}
Pas de retour à la ligne

2018-03-14 21:58 UTC, qmachard commented on package.json
> -    "start": "react-native-scripts start",
Comme on a vu ensemble, c'est normal du coup et on n'utilise plus expo

2018-03-20 12:24 UTC, merged